name: testorama
favicon: null
layout_spectrum: 0.10561977047473192
typography_spectrum: 0.3502012323588133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9405020500998944
  lightness: 0.14406706695444882
  saturation: 0.628594326088205
  rhythmicContrast: 0.4418938218150288
purpose: []
